version: '3.8'

services:
  # SQL Server Service
  mssql:
    container_name: mssql_container
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - SA_PASSWORD=Password123*
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - productmanager-network
    restart: always
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1' | /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Password123*"]
      interval: 10s
      timeout: 10s
      retries: 5

  # Web API Service
  webapi:
    container_name: productmanager_webapi
    build:
      context: .
      dockerfile: src/ProductManager.WebApi/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - mssql
    networks:
      - productmanager-network
    restart: always  

networks:
  productmanager-network:
    driver: bridge

volumes:
  mssql-data:
